// Side panels: metadata (§21), filters (§23), inspector (§24), legend, warnings.
import { el, clear } from './dom.js';
import { formatDate, shortSha, formatSourceRef, formatCount } from '../lib/format.js';
import { colorFor } from '../lib/colors.js';
import { incidentEdges, PROVENANCE_WITH, PROVENANCE_WITHOUT } from '../lib/graph-model.js';

const FACET_LABELS = {
  type: 'Type',
  context: 'Context',
  status: 'Status',
  provenance: 'Provenance',
  relation: 'Relation',
  edgeStatus: 'Relation status',
};

const PROVENANCE_LABELS = {
  [PROVENANCE_WITH]: 'has sources',
  [PROVENANCE_WITHOUT]: 'no sources',
};

function field(label, valueNode, extraClass = '') {
  return el('div', { class: `field ${extraClass}`.trim() }, [
    el('div', { class: 'field-label', text: label }),
    el('div', { class: 'field-value' }, [valueNode]),
  ]);
}

function textOrDash(value) {
  return document.createTextNode(value === null || value === undefined || value === '' ? '—' : String(value));
}

/** Repository / freshness / counts block (CDC §7 and §21). */
export function renderMeta(container, ctx) {
  const { repo, meta, summary, nodeCount, edgeCount, mismatches, fetchedAt, manifestUrl } = ctx;
  clear(container);

  const repoNode = repo
    ? el('a', {
        href: `https://github.com/${repo.owner}/${repo.repo}`,
        target: '_blank',
        rel: 'noreferrer noopener',
        text: `${repo.owner}/${repo.repo}`,
      })
    : el('span', { class: 'mono wrap', text: manifestUrl ?? '—' });
  container.append(field('Repository', repoNode));

  container.append(
    field('Vault Graph', textOrDash(meta.version ? `Vault Graph ${meta.version}` : 'Vault Graph (version unknown)'))
  );

  container.append(
    field('Graph generated', textOrDash(formatDate(meta.generatedAt ?? summary.generatedAt ?? null)), 'primary')
  );

  const commit = meta.commit ?? summary.sourceCommit ?? null;
  const commitNode = commit
    ? repo
      ? el('a', {
          class: 'mono',
          href: `https://github.com/${repo.owner}/${repo.repo}/commit/${commit}`,
          target: '_blank',
          rel: 'noreferrer noopener',
          text: shortSha(commit),
        })
      : el('span', { class: 'mono', text: shortSha(commit) })
    : el('span', { text: 'unknown' });
  container.append(field('Source commit', commitNode));

  const counts = el('div', { class: 'counts' }, [
    el('div', { class: 'count' }, [
      el('span', { class: 'count-value', text: formatCount(nodeCount) }),
      el('span', { class: 'count-label', text: 'Nodes' }),
    ]),
    el('div', { class: 'count' }, [
      el('span', { class: 'count-value', text: formatCount(edgeCount) }),
      el('span', { class: 'count-label', text: 'Edges' }),
    ]),
  ]);
  container.append(counts);

  for (const message of mismatches ?? []) {
    container.append(el('p', { class: 'note warn', text: message }));
  }

  if (meta.generatorName) {
    container.append(
      el('p', {
        class: 'note muted',
        text: `Generated by ${meta.generatorType ? `${meta.generatorType}:` : ''}${meta.generatorName}.`,
      })
    );
  }

  container.append(
    el('p', {
      class: 'note secondary',
      text: `Fetched ${formatDate(fetchedAt, { empty: '—' })} — the date that matters is the generation date above.`,
    })
  );
}

/** Warnings / data issues, always visible but never blocking. */
export function renderWarnings(container, warnings) {
  clear(container);
  const list = (warnings ?? []).filter(Boolean);
  container.hidden = list.length === 0;
  if (!list.length) return;
  const details = el('details', { class: 'warnings' }, [
    el('summary', { text: `${list.length} data note${list.length > 1 ? 's' : ''}` }),
    el(
      'ul',
      {},
      list.slice(0, 60).map((w) => el('li', { text: w }))
    ),
  ]);
  container.append(details);
}

/** Type legend (colours are derived from the discovered type names). */
export function renderLegend(container, typeFacet) {
  clear(container);
  if (!typeFacet?.length) return;
  container.append(
    el(
      'div',
      { class: 'legend' },
      typeFacet.slice(0, 24).map((entry) =>
        el('span', { class: 'legend-item' }, [
          el('span', { class: 'swatch', style: `background:${colorFor(entry.value)}` }),
          el('span', { text: entry.value }),
        ])
      )
    )
  );
}

/**
 * Filter panel. Values and counts are discovered from the graph, never
 * hardcoded (CDC §23).
 */
export function renderFilters(container, ctx) {
  const { facets, filters, quickFilters, onToggle, onReset, onQuick } = ctx;
  clear(container);

  if (quickFilters?.length) {
    container.append(
      el('div', { class: 'quick-row' }, [
        el('span', { class: 'quick-label', text: 'Quick' }),
        ...quickFilters.map((q) =>
          el('button', {
            type: 'button',
            class: `chip quick${q.active ? ' active' : ''}`,
            text: `${q.label} (${q.count})`,
            title: q.title ?? '',
            onclick: () => onQuick(q),
          })
        ),
      ])
    );
  }

  for (const facetKey of ['type', 'context', 'status', 'provenance', 'relation', 'edgeStatus']) {
    const values = facets[facetKey];
    if (!values || !values.length) continue;
    const selected = filters[facetKey] ?? new Set();
    const group = el('section', { class: 'facet' }, [
      el('div', { class: 'facet-head' }, [
        el('h3', { text: FACET_LABELS[facetKey] ?? facetKey }),
        selected.size
          ? el('button', {
              type: 'button',
              class: 'link-button',
              text: 'clear',
              onclick: () => onReset(facetKey),
            })
          : null,
      ]),
      el(
        'div',
        { class: 'chips' },
        values.map((entry) => {
          const active = selected.has(entry.value);
          const label = facetKey === 'provenance' ? PROVENANCE_LABELS[entry.value] ?? entry.value : entry.value;
          const chip = el('button', {
            type: 'button',
            class: `chip${active ? ' active' : ''}`,
            'aria-pressed': active ? 'true' : 'false',
            onclick: () => onToggle(facetKey, entry.value),
          }, [
            facetKey === 'type'
              ? el('span', { class: 'swatch', style: `background:${colorFor(entry.value)}` })
              : null,
            el('span', { text: label }),
            el('span', { class: 'chip-count', text: String(entry.count) }),
          ]);
          return chip;
        })
      ),
    ]);
    container.append(group);
  }
}

function sourceItem(source, linkFor) {
  const label = formatSourceRef(source);
  const href = linkFor ? linkFor(source) : null;
  const main = href
    ? el('a', { class: 'mono', href, target: '_blank', rel: 'noreferrer noopener', text: label })
    : el('span', { class: 'mono', text: label });
  return el('li', {}, [main, source.heading ? el('span', { class: 'muted', text: ` — ${source.heading}` }) : null]);
}

function sourcesBlock(item, linkFor) {
  if (!item.sources.length) {
    return el('p', { class: 'note warn', text: 'No source recorded for this item.' });
  }
  return el(
    'ul',
    { class: 'sources' },
    item.sources.map((s) => sourceItem(s, linkFor))
  );
}

function edgeRow(graph, edge, direction, onNavigate, onSelectEdge) {
  const otherId = direction === 'out' ? edge.to : edge.from;
  const other = graph.nodeById.get(otherId);
  return el('li', { class: 'edge-row' }, [
    el('button', {
      type: 'button',
      class: 'link-button relation',
      text: edge.relation,
      title: `Select relation ${edge.id}`,
      onclick: () => onSelectEdge(edge.id),
    }),
    el('span', { class: 'arrow', text: direction === 'out' ? '→' : '←' }),
    el('button', {
      type: 'button',
      class: 'link-button node-link',
      text: other ? other.label : otherId,
      onclick: () => onNavigate(otherId),
    }),
    el('span', { class: 'tag', text: edge.status }),
    edge.sources.length ? null : el('span', { class: 'tag warn', text: 'no source' }),
  ]);
}

/** Node / edge inspector (CDC §24, §25). */
export function renderInspector(container, ctx) {
  const { graph, selection, linkFor, onNavigate, onSelectEdge, emptyHint } = ctx;
  clear(container);

  if (!selection) {
    container.append(el('p', { class: 'muted', text: emptyHint ?? 'Select a node or a relation.' }));
    return;
  }

  if (selection.kind === 'node') {
    const node = graph.nodeById.get(selection.id);
    if (!node) {
      container.append(el('p', { class: 'muted', text: 'This node is no longer in the graph.' }));
      return;
    }
    container.append(el('h2', { class: 'inspector-title', text: node.label }));
    container.append(el('div', { class: 'mono muted small wrap', text: node.id }));
    container.append(field('Type', el('span', { class: 'tag type' }, [
      el('span', { class: 'swatch', style: `background:${colorFor(node.type)}` }),
      el('span', { text: node.type }),
    ])));
    container.append(field('Context', textOrDash(node.context)));
    container.append(field('Status', el('span', { class: 'tag', text: node.status })));
    if (node.reason) container.append(field('Reason', textOrDash(node.reason), 'reason'));
    if (node.aliases.length) container.append(field('Aliases', textOrDash(node.aliases.join(', '))));

    container.append(el('h3', { class: 'section-title', text: 'Sources' }));
    container.append(sourcesBlock(node, linkFor));

    const { incoming, outgoing } = incidentEdges(graph, node.id);
    container.append(el('h3', { class: 'section-title', text: `Incoming edges (${incoming.length})` }));
    container.append(
      incoming.length
        ? el('ul', { class: 'edges' }, incoming.map((e) => edgeRow(graph, e, 'in', onNavigate, onSelectEdge)))
        : el('p', { class: 'muted', text: 'None.' })
    );
    container.append(el('h3', { class: 'section-title', text: `Outgoing edges (${outgoing.length})` }));
    container.append(
      outgoing.length
        ? el('ul', { class: 'edges' }, outgoing.map((e) => edgeRow(graph, e, 'out', onNavigate, onSelectEdge)))
        : el('p', { class: 'muted', text: 'None.' })
    );
    if (!incoming.length && !outgoing.length) {
      container.append(
        el('p', {
          class: node.reason ? 'note' : 'note warn',
          text: node.reason
            ? 'Isolated node — a reason is recorded above.'
            : 'Isolated node with no recorded reason (CDC §14: zero unexplained orphans).',
        })
      );
    }
    return;
  }

  const edge = graph.edgeById.get(selection.id);
  if (!edge) {
    container.append(el('p', { class: 'muted', text: 'This relation is no longer in the graph.' }));
    return;
  }
  const from = graph.nodeById.get(edge.from);
  const to = graph.nodeById.get(edge.to);
  container.append(el('h2', { class: 'inspector-title', text: edge.relation }));
  container.append(el('div', { class: 'mono muted small wrap', text: edge.id }));
  container.append(
    field(
      'From',
      el('button', {
        type: 'button',
        class: 'link-button node-link',
        text: from ? from.label : edge.from,
        onclick: () => onNavigate(edge.from),
      })
    )
  );
  container.append(
    field(
      'To',
      el('button', {
        type: 'button',
        class: 'link-button node-link',
        text: to ? to.label : edge.to,
        onclick: () => onNavigate(edge.to),
      })
    )
  );
  container.append(field('Status', el('span', { class: 'tag', text: edge.status })));
  container.append(el('h3', { class: 'section-title', text: 'Sources' }));
  container.append(sourcesBlock(edge, linkFor));
}
